---
# without-operator.yaml - Free Tier Demo Cluster Scenario
# This scenario demonstrates kube9-vscode Free Tier functionality without the kube9-operator.
# It includes basic workloads suitable for testing Free Tier features.

# Application Namespace
# This namespace contains all demo workloads for the Free Tier scenario
apiVersion: v1
kind: Namespace
metadata:
  name: default-app
  labels:
    scenario: without-operator
---
# Demo Application Deployment
# Simple nginx-based deployment demonstrating basic workload management
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: default-app
  labels:
    app: demo-app
    scenario: without-operator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: app
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
# Demo Application Service
# ClusterIP service exposing the demo-app deployment
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: default-app
  labels:
    app: demo-app
    scenario: without-operator
spec:
  selector:
    app: demo-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
# StatefulSet Example
# Demonstrates stateful workload management in Free Tier
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-statefulset
  namespace: default-app
  labels:
    app: demo-statefulset
    scenario: without-operator
spec:
  serviceName: demo-statefulset
  replicas: 2
  selector:
    matchLabels:
      app: demo-statefulset
  template:
    metadata:
      labels:
        app: demo-statefulset
    spec:
      containers:
      - name: app
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
# StatefulSet Service
# Headless service for StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: demo-statefulset
  namespace: default-app
  labels:
    app: demo-statefulset
    scenario: without-operator
spec:
  clusterIP: None
  selector:
    app: demo-statefulset
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
# DaemonSet Example
# Demonstrates daemon workload management in Free Tier
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: demo-daemonset
  namespace: default-app
  labels:
    app: demo-daemonset
    scenario: without-operator
spec:
  selector:
    matchLabels:
      app: demo-daemonset
  template:
    metadata:
      labels:
        app: demo-daemonset
    spec:
      containers:
      - name: app
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
# ConfigMap Example
# Demonstrates configuration management in Free Tier
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  namespace: default-app
  labels:
    app: demo-app
    scenario: without-operator
data:
  app.properties: |
    # Demo configuration file
    app.name=demo-app
    app.version=1.0.0
    app.environment=demo
  config.yaml: |
    # Demo YAML configuration
    server:
      port: 8080
      host: localhost
---
# Secret Example
# Demonstrates secret management in Free Tier
# WARNING: This contains dummy data for demo purposes only - NOT real credentials
apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
  namespace: default-app
  labels:
    app: demo-app
    scenario: without-operator
type: Opaque
data:
  # Base64 encoded "demo-password" - dummy data for demo purposes only
  password: ZGVtby1wYXNzd29yZA==
  # Base64 encoded "demo-api-key" - dummy data for demo purposes only
  api-key: ZGVtby1hcGkta2V5
